USE prog3;

SET SQL_SAFE_UPDATES = 0;

DELETE FROM ATENCION_MEDICA;
DELETE FROM CITA;
DELETE FROM MASCOTA;
DELETE FROM HORARIO_ATENCION;
DELETE FROM CLIENTE;
DELETE FROM VETERINARIO;
DELETE FROM RECEPCIONISTA;
DELETE FROM ADMINISTRADOR;  
DELETE FROM USUARIO;

SET SQL_SAFE_UPDATES = 1;